### ISSUE TITLE
Add settings link to the plugin page

### ISSUE THREAD

**Issue by growdev** [sugarcalendar/sugar-event-calendar#112]
![screen shot 2017-08-09 at 11 34 39 am](https://user-images.githubusercontent.com/290886/29132732-c4965a84-7cf6-11e7-8053-a9c3d86f4fd1.png)

**Comment by JJJ** [comment]
In `release/2.0` these settings were switched to using the WordPress core settings, and there is no dedicated Sugar Calendar settings page.

There will be a need for license key entry, and I can imagine a need for other more complex settings pages to exist, but I'd like to tackle those in a different issue.

Closing this one under the 2.0 milestone since that's where it's most applicable going forward.
