### ISSUE TITLE
Make plugin name consistent

### ISSUE THREAD

**Issue by growdev** [sugarcalendar/sugar-event-calendar#113]
This page uses singular event: "Sugar Event Calendar" 
https://pippinsplugins.com/products/sugar-event-calendar/

The plugin name uses plural event:  "Sugar Events Calendar"
![screen shot 2017-08-29 at 10 26 57 am](https://user-images.githubusercontent.com/290886/29829279-980826ec-8ca4-11e7-9f85-fb37ed3171d9.png)

@pippinsplugins which do you prefer?  I think singular "Event".

**Comment by JJJ** [comment]
Going with "Sugar Calendar" in as many public places as possible.

One caveat is the WordPress.org plugin slug, which is literally `sugar-event-calendar`. I'm not sure we can change plugin slugs, basically ever... but if we wanted to work around it, we could keep a copy of the plugin also at `sugar-calendar` and migrate users to the new location.

----

The plan (as of today) is to slowly and methodically move away from "event" verbiage over a several year period of time. @pippinsplugins pointed out that there's some SEO benefit from keeping it around for a while, which I tend to agree with.

----

This is already fixed in the `release/2.0` branch. 👍
