### ISSUE TITLE
Restructure settings and integrations

### ISSUE THREAD

**Issue by SDavisMedia** [sugarcalendar/sugar-event-calendar#119]
A full restructure may not be a popular idea, but I think the settings need a slight enhancement at a minimum. I'll explain.

I'm a brand new user of Sugar Event Calendar and I rarely use Restrict Content Pro. On a new test site, I started to set them both up from scratch. In the Events menu, I saw a **Restrict Access** submenu. I went there and I actually felt lost. I know enough about RCP to _assume_ that page was part of some sort of integration, but I read every word on the page and nothing referred to RCP specifically. To confirm, I deactivated RCP to see if the page would go away. 

Then I went to the Settings page. It was pretty uneventful, which is fine. But I couldn't figure out a reason why it wasn't tabbed. Without RCP, perhaps no tab is needed. All good. But with RCP there having its own dedicated page, it makes me wonder what future integration will either demand the same treatment, or even worse, use a different method to display its settings.

I think SEC can take a page out of EDD's book and use tabs (when necessary). With that, you can introduce an **Integrations** tab (or whatever you want to call it) and have subsections, one of which would be RCP.

Please remember, this is from the POV of a person who doesn't use either of these plugins. I'm pretty much brand new to them both.

Thoughts?

**Comment by JJJ** [comment]
Sugar Calendar 2.0 basically abolishes the settings page, because these settings already exist in WordPress, or can be derived from the locale of the site.

I also could not think of newer, equally important settings to add here.

All of that said, the EDD approach of having everything live under one top level admin menu is really popular, but also isn’t future proof. It’s akin to an iOS app having an internal settings page instead of using the core API in the Settings app. (There are use cases for both.)

One place that a settings page _does_ become a requirement is add-ons. I believe we should provide a robust location and set of tabs/tools for dividing settings up into sections, as that pattern also works really well for users and for the project.

So, I’m on board with tabs, we just need settings to occupy them, and we need functions/filters to make registering them there easy.

I have some code in WP User Profiles that does this pretty elegantly already. It’s worth using, IMO.

**Comment by JJJ** [comment]
Merged into `release/2.0`.

Since there is only 1 screen/section/subsection right now, it's pretty sparse, but the foundation is in.

Closing, and let's make new issues for individual bugs as they crop up.
